import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";



const poppins = Poppins({
  weight: ['400', '600', '500'],
  subsets: ['latin'],
  display: 'swap',
});
export const metadata: Metadata = {
  title: "Company Name",
  description: "Generated by create next app", 
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
